#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Aleix Pol Gonzalez <aleixpol@kde.org>

"""Generate a KDE element and update its dependencies from a CMake trace."""

from __future__ import annotations

import argparse
import json
import lzma
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import bst_search_file
import cmake_dependencies
import gitlab
import tomllib
import yaml

GENERATED_MARKER = "# Generated by utils/update_kde_element.py"
OSC_ESCAPE = re.compile(r"\x1b\].*?(?:\x07|\x1b\\)")
PACKAGE_PROJECT = "teams/ci-artifacts/suse-qt6.11"
BUILD_DEPENDENCIES = [
    "freedesktop-sdk.bst:public-stacks/buildsystem-cmake.bst",
]
PROVIDER_OVERRIDES = {
    "FindBISON.cmake": {
        "freedesktop-sdk.bst:components/bison.bst",
    },
    "FindBoost.cmake": {
        "components/boost.bst",
    },
    "FindClang.cmake": {
        "freedesktop-sdk.bst:components/llvm.bst",
    },
    "FindDocBookXML4.cmake": {
        "freedesktop-sdk.bst:components/docbook-xml.bst",
    },
    "FindFLEX.cmake": {
        "freedesktop-sdk.bst:components/flex.bst",
    },
    "FindDoxygen.cmake": {
        "freedesktop-sdk.bst:components/doxygen.bst",
    },
    "FindLibArchive.cmake": {
        "freedesktop-sdk.bst:components/libarchive.bst",
    },
    "FindPerlModules.cmake": {
        "components/perl-uri-escape.bst",
    },
    "FindPerl.cmake": {
        "freedesktop-sdk.bst:components/perl.bst",
    },
    "FindPython.cmake": {
        "freedesktop-sdk.bst:components/python3.bst",
    },
    "FindPython3.cmake": {
        "freedesktop-sdk.bst:components/python3.bst",
    },
    "FindQRencode.cmake": {
        "components/qrencode.bst",
    },
    "FindRust.cmake": {
        "freedesktop-sdk.bst:components/rust.bst",
    },
    "FindSensors.cmake": {
        "components/lm-sensors.bst",
    },
    "FindVulkan.cmake": {
        "freedesktop-sdk.bst:components/vulkan-headers.bst",
        "freedesktop-sdk.bst:components/vulkan-icd-loader.bst",
    },
    "FindWayland.cmake": {
        "freedesktop-sdk.bst:components/wayland.bst",
    },
    "FindX11.cmake": {
        "freedesktop-sdk.bst:components/xorg-lib-x11.bst",
    },
    "FindZLIB.cmake": {
        "freedesktop-sdk.bst:components/zlib.bst",
    },
}
NON_FATAL_FIND_MODULES = {"FindHSPELL.cmake"}
PROJECT_DEPENDENCIES = {
    "breeze-icons": {"freedesktop-sdk.bst:components/python3-lxml.bst"},
    # Enabled only by our kde-builder override, so KDE CI's default trace does
    # not contain this find_package() call.
    "konsole": {
        "components/qcoro.bst",
        "kde/kapsule.bst",
    },
}
TARGET_ELEMENTS = {"appstream": "appstreamqt.bst"}
DEPENDENCIES_TARGET = "os/deps-kde.bst"


@dataclass(frozen=True)
class Project:
    name: str
    path: str
    repository: str
    branch: str
    build: bool
    dependencies: tuple[str, ...]
    cmake_options: str = ""
    group: str = ""


@dataclass(frozen=True)
class ProjectTrace:
    paths: set[str]
    find_candidates: dict[str, set[str]]
    revision: str | None
    cargo_sources: list[dict[str, Any]]


def kde_builder_projects(requested: list[str]) -> dict[str, Project]:
    def query(name: str) -> str:
        command = [
            "kde-builder",
            "--rc-file",
            "kde-builder.yaml.in",
            "--query",
            name,
            "--no-colorful-output",
            *requested,
        ]
        try:
            completed = subprocess.run(
                command,
                check=True,
                capture_output=True,
                text=True,
            )
        except subprocess.CalledProcessError as error:
            message = OSC_ESCAPE.sub("", error.stderr).strip()
            raise ValueError(message or "kde-builder failed") from error
        return OSC_ESCAPE.sub("", completed.stdout)

    def query_values(name: str) -> dict[str, str]:
        values = {}
        for line in query(name).splitlines():
            key, separator, value = line.partition(":")
            if separator:
                values[key] = value.strip()
        return values

    output = query("project-info")
    output_lines = output.splitlines()
    while output_lines and (not output_lines[0] or output_lines[0][0].isspace()):
        diagnostic = output_lines.pop(0).strip()
        if diagnostic:
            print(diagnostic, file=sys.stderr)
    output = "\n".join(output_lines)
    cmake_options = query_values("cmake-options")
    groups = query_values("group")
    data = yaml.safe_load(output)
    if not isinstance(data, dict):
        raise TypeError("kde-builder did not return a project mapping")
    projects: dict[str, Project] = {}
    for name, value in data.items():
        projects[name] = Project(
            name=name,
            path=value.get("path") or "",
            repository=value.get("repository") or "",
            branch=value.get("branch") or "master",
            build=value.get("build") is True,
            dependencies=tuple(value.get("dependencies") or []),
            cmake_options=cmake_options.get(name, ""),
            group=groups.get(name, ""),
        )
    return projects


def target_names(value: str) -> list[str]:
    path = Path(value)
    if not path.is_file():
        return [value]
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict) or not isinstance(document.get("targets"), list):
        raise ValueError(f"{path} does not contain a targets list")
    targets = document["targets"]
    if not targets or not all(isinstance(target, str) for target in targets):
        raise ValueError(f"{path} contains an invalid targets list")
    return targets


def read_trace(
    path: Path,
    cargo_locks: set[str] | None = None,
    project_name: str | None = None,
) -> list[dict[str, Any]]:
    stream = lzma.open(path, "rb") if path.suffix == ".xz" else path.open("rb")
    with stream:
        return cmake_dependencies.processLog(
            stream, cargoLocks=cargo_locks, cargoProject=project_name
        )


def cargo_ref(contents: bytes, path: str) -> list[dict[str, str]]:
    try:
        lock = tomllib.loads(contents.decode("utf-8"))
    except (UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
        raise ValueError(f"malformed {path}") from error
    result = []
    for package in lock.get("package", []):
        if "source" not in package:
            continue
        checksum = package.get("checksum")
        if not checksum:
            raise ValueError(
                f"{path} contains {package.get('name', 'a crate')} without a checksum"
            )
        result.append(
            {
                "kind": "registry",
                "name": str(package["name"]),
                "version": str(package["version"]),
                "sha": str(checksum),
            }
        )
    return sorted(result, key=lambda crate: (crate["name"], crate["version"]))


def registry_versions(registry) -> dict[tuple[str, str], str]:
    versions: dict[tuple[str, str], str] = {}
    timestamps: dict[tuple[str, str], int] = {}
    for package in registry.packages.list(iterator=True):
        branch, timestamp_text = package.version.rsplit("-", 1)
        key = (package.name, branch)
        timestamp = int(timestamp_text)
        if timestamp > timestamps.get(key, 0):
            timestamps[key] = timestamp
            versions[key] = package.version
    return versions


def cmake_paths(dependencies: list[dict[str, Any]]) -> set[str]:
    pkg_config_projects = {
        dependency.get("project", "").casefold()
        for dependency in dependencies
        if any(path.endswith(".pc") for path in dependency.get("files", []))
    }
    return {
        path
        for dependency in dependencies
        if not dependency.get("missing")
        for path in dependency.get("files", [])
        if dependency.get("explicit")
        and not (
            (
                dependency.get("pkg_config")
                or dependency.get("project", "").casefold() in pkg_config_projects
            )
            and Path(path).name.startswith("Find")
            and path.endswith(".cmake")
        )
    }


def cmake_find_candidates(
    dependencies: list[dict[str, Any]],
) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for dependency in dependencies:
        files = dependency.get("files", [])
        modules = {
            Path(path).name
            for path in files
            if Path(path).name.startswith("Find") and path.endswith(".cmake")
        }
        if not modules:
            continue
        for module in modules:
            if not dependency.get("explicit"):
                continue
            result.setdefault(module, set()).update(dependency.get("candidates", []))
    return result


def render_element(
    project: Project,
    dependencies: set[str],
    trace: ProjectTrace,
) -> str:
    source = {
        "kind": "git_repo",
        "url": project.repository,
        "track": "master",
    }
    if trace.revision:
        source["ref"] = trace.revision
    rust = "freedesktop-sdk.bst:components/rust.bst"
    build_dependencies = [*BUILD_DEPENDENCIES]
    if trace.cargo_sources or rust in dependencies:
        build_dependencies.append(rust)
    document = {
        "kind": "cmake",
        "build-depends": build_dependencies,
        "depends": sorted(dependencies - {rust}),
        "variables": {"cmake-local": project.cmake_options},
        "sources": [source, *trace.cargo_sources],
    }
    return render_document(document)


def render_stack(elements: list[str]) -> str:
    return render_document({"kind": "stack", "depends": elements})


def render_document(document: dict[str, Any]) -> str:
    header = (
        "# SPDX-FileCopyrightText: none\n"
        "# SPDX-License-Identifier: CC0-1.0\n"
        f"{GENERATED_MARKER}\n"
    )
    return header + yaml.safe_dump(document, sort_keys=False)


def write_target_stacks(
    selectors: list[str],
    projects: dict[str, Project],
    generated_projects: set[str],
    *,
    dry_run: bool,
) -> None:
    element_dir = Path.cwd() / "elements"

    def project_element(name: str) -> str | None:
        project = projects.get(name)
        if project is None or not project.build:
            return None
        if name in generated_projects:
            return f"kde/{name}.bst"
        target_element = TARGET_ELEMENTS.get(name)
        if target_element and (element_dir / target_element).is_file():
            return target_element
        component = f"components/{name}.bst"
        return component if (element_dir / component).is_file() else None

    top_level: list[str] = []
    for selector in selectors:
        element = project_element(selector)
        if element:
            top_level.append(element)
            continue
        members = sorted(
            {
                member
                for name, project in projects.items()
                if project.group == selector
                if (member := project_element(name))
            }
        )
        if members:
            write_element(
                element_dir / "kde" / f"{selector}.bst",
                render_stack(members),
                dry_run,
            )
            top_level.append(f"kde/{selector}.bst")
    write_element(
        element_dir / "kde.bst",
        render_stack(list(dict.fromkeys(top_level))),
        dry_run,
    )


def write_element(path: Path, contents: str, dry_run: bool) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == contents:
            return False
        if GENERATED_MARKER not in current:
            raise ValueError(f"refusing to replace manually maintained element {path}")
    if dry_run:
        print(contents)
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")
    return True


@dataclass
class Resolution:
    dependencies: set[str] = field(default_factory=set)
    warnings: list[str] = field(default_factory=list)
    missing_find_providers: set[str] = field(default_factory=set)


class DependencyResolver:
    def __init__(
        self,
        traces: dict[str, ProjectTrace],
        kde_providers: dict[str, set[str]],
    ) -> None:
        self.kde_providers = kde_providers
        self.local_projects = set(traces)
        paths = set().union(*(trace.paths for trace in traces.values()))
        paths.update(
            candidate
            for trace in traces.values()
            for candidates in trace.find_candidates.values()
            for candidate in candidates
        )
        root = Path.cwd()
        bst_search_file.build_artifacts(root, DEPENDENCIES_TARGET)
        self.providers = bst_search_file.providers_for_paths(
            root, DEPENDENCIES_TARGET, paths
        )

    def resolve(self, project: Project, trace: ProjectTrace) -> Resolution:
        resolution = Resolution(
            dependencies=set(PROJECT_DEPENDENCIES.get(project.name, set()))
        )
        for path in sorted(trace.paths):
            filename = Path(path).name
            provider_override = PROVIDER_OVERRIDES.get(filename)
            if provider_override:
                resolution.dependencies.update(provider_override)
                continue
            kde_found = self.kde_providers.get(path, set())
            if not kde_found:
                kde_found = self.kde_providers.get(filename, set())
            if len(kde_found) == 1:
                kde_project = next(iter(kde_found))
                if kde_project in self.local_projects:
                    resolution.dependencies.add(f"kde/{kde_project}.bst")
                    continue
            if len(kde_found) > 1:
                resolution.warnings.append(
                    f"{path}: provided by multiple KDE projects: "
                    f"{', '.join(sorted(kde_found))}"
                )
                continue
            found = self.providers.get(path, set())
            is_find_module = filename.startswith("Find") and filename.endswith(".cmake")
            is_project_file = path.startswith("/builds/") and "/_install/" not in path
            if is_find_module and (
                len(found) != 1
                or all(provider.endswith(":components/cmake.bst") for provider in found)
            ):
                found = {
                    provider
                    for candidate in trace.find_candidates.get(filename, set())
                    for provider in self.providers.get(candidate, set())
                }
                if is_project_file and len(found) != 1:
                    resolution.warnings.append(
                        f"{project.name} {path}: {', '.join(sorted(found)) or 'not found'}; dependency not added"
                    )
                    continue
            elif is_project_file:
                continue
            if len(found) == 1:
                resolution.dependencies.update(found)
            elif is_find_module and filename not in NON_FATAL_FIND_MODULES:
                resolution.missing_find_providers.add(filename)
            else:
                resolution.warnings.append(
                    f"{project.name} {path}: {', '.join(sorted(found)) or 'not found'}"
                )

        # ECM's CI trace includes its module tests, which require Qt, LLVM, Python,
        # and Vulkan. Keeping them with tests disabled creates a cycle when ECM
        # replaces SDK ECM and needlessly changes every Qt artifact key.
        if (
            project.name == "extra-cmake-modules"
            and "-DBUILD_TESTING=OFF" in project.cmake_options.split()
        ):
            resolution.dependencies.difference_update(
                {
                    "freedesktop-sdk.bst:components/llvm.bst",
                    "freedesktop-sdk.bst:components/python3.bst",
                    "freedesktop-sdk.bst:components/vulkan-headers.bst",
                    "freedesktop-sdk.bst:components/vulkan-icd-loader.bst",
                    "qt/qtbase.bst",
                    "qt/qtdeclarative.bst",
                    "qt/qttools.bst",
                }
            )

        return resolution


def collect_gitlab_data(
    projects: dict[str, Project],
) -> tuple[dict[str, ProjectTrace], dict[str, set[str]]]:
    cache_dir = Path.cwd() / ".cmake-traces"
    requested = [
        project
        for project in projects.values()
        if project.build and project.repository.startswith("kde:")
    ]
    if not requested:
        raise ValueError("kde-builder selected no KDE projects")
    server = gitlab.Gitlab("https://invent.kde.org")
    registry = server.projects.get(PACKAGE_PROJECT)
    versions = registry_versions(registry)
    cache_dir.mkdir(parents=True, exist_ok=True)

    def download_package_file(
        identifier: str,
        branch: str,
        filename: str,
    ) -> Path:
        normalized_branch = branch.replace("/", "-")
        version = versions.get((identifier, normalized_branch))
        if not version:
            raise ValueError(f"no CI package for {identifier} on branch {branch}")
        destination = cache_dir / f"{identifier}-{version}-{filename}"
        if destination.is_file():
            return destination
        try:
            response = registry.generic_packages.download(
                package_name=identifier,
                package_version=version,
                file_name=filename,
            )
        except gitlab.GitlabGetError as error:
            raise ValueError(
                f"{filename} is unavailable for {identifier} on branch {branch}"
            ) from error
        destination.write_bytes(response)
        return destination

    def cargo_sources(
        project: Project,
        revision: str,
        lock_paths: set[str],
    ) -> list[dict[str, Any]]:
        cache_path = cache_dir / f"{project.name}-{revision}-cargo-sources.json"
        if cache_path.is_file():
            cached = json.loads(cache_path.read_text(encoding="utf-8"))
            if not isinstance(cached, list):
                raise ValueError(f"invalid Cargo source cache {cache_path}")
            return cached
        repository = server.projects.get(project.path)
        sources = []
        for path in sorted({"Cargo.lock", *lock_paths}):
            try:
                contents = repository.files.raw(file_path=path, ref=revision)
            except gitlab.GitlabGetError as error:
                if error.response_code == 404:
                    continue
                raise
            sources.append(
                {
                    "kind": "cargo2",
                    "cargo-lock": path,
                    "ref": cargo_ref(contents, path),
                }
            )
        cache_path.write_text(json.dumps(sources), encoding="utf-8")
        return sources

    def kde_trace_providers(names: set[str]) -> dict[str, set[str]]:
        providers: dict[str, set[str]] = {}
        for name in sorted(names):
            project = projects.get(name)
            if project is None or not project.repository:
                continue
            try:
                trace = download_package_file(
                    name,
                    project.branch,
                    "cmake-trace.log.xz",
                )
            except ValueError as error:
                print(f"warning: {error}", file=sys.stderr)
                continue
            with lzma.open(trace, "rb") as stream:
                provided_files = cmake_dependencies.processProvidedFiles(stream)
            for provided in provided_files:
                providers.setdefault(provided, set()).add(name)
        return providers

    traces: dict[str, ProjectTrace] = {}
    for project in requested:
        try:
            trace = download_package_file(
                project.name,
                "master",
                "cmake-trace.log.xz",
            )
        except ValueError as error:
            print(f"warning: {error}", file=sys.stderr)
            continue
        cargo_locks: set[str] = set()
        trace_dependencies = read_trace(trace, cargo_locks, project.name)
        metadata_path = download_package_file(
            project.name,
            "master",
            "metadata.json",
        )
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        revision = metadata.get("gitRevision")
        sources = []
        if isinstance(revision, str):
            sources = cargo_sources(
                project,
                revision,
                cargo_locks,
            )
        else:
            revision = None
        traces[project.name] = ProjectTrace(
            cmake_paths(trace_dependencies),
            cmake_find_candidates(trace_dependencies),
            revision,
            sources,
        )

    dependency_names = {
        dependency for project in requested for dependency in project.dependencies
    }
    kde_providers = kde_trace_providers(dependency_names)
    return traces, kde_providers


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "project", help="KDE project name or YAML file containing a targets list"
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    root = Path.cwd()

    try:
        selectors = target_names(args.project)
        projects = kde_builder_projects(selectors)
        traces, kde_providers = collect_gitlab_data(projects)
        resolver = DependencyResolver(traces, kde_providers)
        rendered = {}
        missing_find_providers: set[str] = set()
        for project_name, trace in traces.items():
            project = projects[project_name]
            resolution = resolver.resolve(project, trace)
            missing_find_providers.update(resolution.missing_find_providers)
            for warning in resolution.warnings:
                print(f"warning: {warning}", file=sys.stderr)
            rendered[project_name] = render_element(
                project, resolution.dependencies, trace
            )
        if missing_find_providers:
            names = ", ".join(sorted(missing_find_providers))
            raise ValueError(f"Cannot figure out which element provides: {names}")

        for project_name, contents in rendered.items():
            path = root / "elements" / "kde" / f"{project_name}.bst"
            if write_element(path, contents, args.dry_run):
                if args.dry_run:
                    status = "Would update"
                else:
                    status = "Updated"
                print(f"{status} {path}", file=sys.stderr)
        if Path(args.project).is_file():
            write_target_stacks(selectors, projects, set(traces), dry_run=args.dry_run)
    except (OSError, TypeError, ValueError, RuntimeError, gitlab.GitlabError) as error:
        parser.exit(1, f"error: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
